# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_descr',
            field=models.TextField(default='Add your super descriptive text here...', verbose_name='Descriptive text'),
        ),
    ]
